name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Stop current Docker containers
      run: docker compose -f docker-compose.prod.yml stop

    - name: Update prod.env with GitHub Secrets
      run: |
          sed -i "s|NEXTAUTH_SECRET=.*|NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}|g" prod.env
          sed -i "s|POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}|g" prod.env

    - name: Pull latest changes and update the submodules
      run: |
        git pull
        git submodule update --init --recursive
        git submodule update --remote --recursive

    - name: Replace placeholder with actual URL
      run: sed -i "s|NEXT_PUBLIC_IP_ADDRESS=.*|NEXT_PUBLIC_IP_ADDRESS=http://${{ secrets.URL }}|g" docker-compose.prod.yml

    - name: Build and run Docker containers
      run: docker compose -f docker-compose.prod.yml up --build
